imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: messagebus.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: de

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        # Bootstrap:
        - bootstrap_3_layout.html.twig

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: legacy
        connections:
            legacy:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%legacy_db_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_general_ci
            foh:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%foh_db_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_general_ci
            dtp:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%dtp_db_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_general_ci

    orm:
        default_entity_manager: legacy
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            legacy:
                connection: legacy
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    Legacy:
                        type: xml
                        dir:  "%kernel.root_dir%/config/doctrine/legacy"
                        prefix: AppBundle\Entity\Legacy
            foh:
                connection: foh
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    FOH:
                        type:   xml
                        dir:    "%kernel.root_dir%/config/doctrine/foh"
                        prefix: AppBundle\Entity\FOH
                        alias:  FOH
            dtp:
                connection: dtp
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    FOH:
                        type:   xml
                        dir:    "%kernel.root_dir%/config/doctrine/dtp"
                        prefix: AppBundle\Entity\DTP
                        alias:  DTP

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
