
services:
    lean.query.current_tips:
        class: AppBundle\MessageBus\QueryHandler\GetCurrentTipsHandler
        arguments:
            - '@doctrine.orm.legacy_entity_manager'
        tags:
            - { name: lean.querybus_handler, query: AppBundle\MessageBus\Query\GetCurrentTips }
