app:
    resource: "@AppBundle/Controller/"
    type:     annotation

dtp_standings:
    resource: "@AppBundle/Controller/Dtp/Standings/"
    type:     annotation

dtp_backend:
    resource: "@AppBundle/Controller/Dtp/Backend/"
    type:     annotation
    prefix:   'tipprunde/admin'
